/**
 * levels.js — The 15 handcrafted sectors.
 *
 * GENERATED from tools/level-authoring.mjs, which holds the readable topology
 * diagrams these maps were designed with. The maps below are plain data: edit
 * them here for a quick tweak, or edit the authoring file and regenerate.
 *
 * Map legend (see js/maze.js LEGEND):
 *   #  wall              .  energy node        (space) bare floor
 *   o  power module      P  player spawn       S  Grid Shift terminal
 *   H  Hunter drone      I  Interceptor        N  Sentinel
 *   T  Tracker           W  Wanderer
 *   =  closed gate       -  open gate          ~  retracted bridge span
 *   %  secret bulkhead   *  bonus node (optional — not required to clear)
 *
 * Shift terminals are bound to `shifts[]` in reading order: the first "S" on
 * the map uses shifts[0], the second uses shifts[1], and so on.
 */

export const LEVELS = [
  {
    id: "L01",
    number: 1,
    name: "Cold Boot",
    subtitle: "Siphon online. Drain the grid.",
    hint: "Swipe or use the arrow keys. Collect every energy node to clear the sector.",
    width: 21,
    height: 21,
    targetTime: 68,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o.................o#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...................#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#.........H.........#",
      "#.#####.##.##.#####.#",
      "#.#####.##.##.#####.#",
      "#...................#",
      "#.#####.##.##.#####.#",
      "#.#####.##.##.#####.#",
      "#...................#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#...................#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#.........P.........#",
      "#####################",
    ],
    shifts: [],
    secrets: [],
  },
  {
    id: "L02",
    number: 2,
    name: "Handshake",
    subtitle: "The grid notices you.",
    hint: "Power modules make drones vulnerable for eight seconds. Chain them for bigger scores.",
    width: 21,
    height: 21,
    targetTime: 72,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o.................o#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#.......##.##.......#",
      "#.#####.##.##.#####.#",
      "#.#####.##.##.#####.#",
      "#o.................o#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#.##......H......##.#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#...................#",
      "#.#####.##.##.#####.#",
      "#.#####.##.##.#####.#",
      "#.......##.##.......#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#.........P.........#",
      "#####################",
    ],
    shifts: [],
    secrets: [],
  },
  {
    id: "L03",
    number: 3,
    name: "Deadlock",
    subtitle: "It stopped following. It started predicting.",
    hint: "Interceptors aim at where you are heading. Change direction to break their lead.",
    width: 21,
    height: 21,
    targetTime: 75,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o.................o#",
      "#.##.########.##.##.#",
      "#.##.########.##.##.#",
      "#...................#",
      "#.#####.#####.#####.#",
      "#.#####.#####.#####.#",
      "#....##...I...##....#",
      "#.##.##.#####.##.##.#",
      "#.##.##.#####.##.##.#",
      "#...................#",
      "#.##.##.#####.##.##.#",
      "#.##.##.#####.##.##.#",
      "#....##.......##....#",
      "#.#####.#####.#####.#",
      "#.#####.#####.#####.#",
      "#...................#",
      "#.##.########.##.##.#",
      "#.##.########.##.##.#",
      "#o........P.........#",
      "#####################",
    ],
    shifts: [],
    secrets: [],
  },
  {
    id: "L04",
    number: 4,
    name: "First Rotation",
    subtitle: "Stop running. Start rewriting.",
    hint: "Touch a violet terminal to rotate that junction 90°. Fifteen second cooldown — spend it well.",
    width: 21,
    height: 21,
    targetTime: 78,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o.................o#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#.........H.........#",
      "#.#####.#####.#####.#",
      "#.#####.#####.#####.#",
      "#...................#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#......S##.##.......#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#.........I.........#",
      "#.#####.#####.#####.#",
      "#.#####.#####.#####.#",
      "#...................#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#o........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"rotate","cx":7,"cy":10,"size":5,"label":"Junction Delta"},
    ],
    secrets: [],
  },
  {
    id: "L05",
    number: 5,
    name: "Bulkhead",
    subtitle: "Some doors only open for you.",
    hint: "Gate terminals seal and unseal routes. Trap a drone behind one and take the sector.",
    width: 21,
    height: 21,
    targetTime: 80,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o.................o#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#.........H.........#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...................#",
      "#.#####.#####.#####.#",
      "#.#####.#####.#####.#",
      "#...N...--S--.......#",
      "#.#####.#####.#####.#",
      "#.#####.#####.#####.#",
      "#...................#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...................#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#o........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"gate","label":"Corridor Seals","cells":[[8,10],[9,10],[11,10],[12,10]]},
    ],
    secrets: [],
  },
  {
    id: "L06",
    number: 6,
    name: "Span",
    subtitle: "Build the road under your feet.",
    hint: "Bridge terminals extend a temporary walkway. It retracts after seven seconds — do not linger.",
    width: 21,
    height: 21,
    targetTime: 82,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o........I........o#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...................#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#.......##.##.......#",
      "#.##.~~.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#W........S.........#",
      "#.##.##.##.##.~~.##.#",
      "#.##.##.##.##.##.##.#",
      "#.......##.##.......#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...................#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#o........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"bridge","label":"Span Extend","cells":[[5,8],[6,8],[14,11],[15,11]]},
    ],
    secrets: [],
  },
  {
    id: "L07",
    number: 7,
    name: "Crosstalk",
    subtitle: "Three patrols. Two terminals. One route.",
    hint: "Secret compartments hide bonus nodes. Watch for bulkheads that do not match the walls.",
    width: 21,
    height: 21,
    targetTime: 88,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o........H........o#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#...................#",
      "#.#####.##.##.#####.#",
      "#.#####.##.##.#####.#",
      "#......S............#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...I...##.##...N...#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#............S......#",
      "#.#####.##.##.#####.#",
      "#.#####.##.##.#####.#",
      "#...................#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#o........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"rotate","cx":7,"cy":7,"size":5,"label":"Junction Alpha"},
      {"type":"rotate","cx":13,"cy":13,"size":5,"ccw":true,"label":"Junction Omega"},
    ],
    secrets: [],
  },
  {
    id: "L08",
    number: 8,
    name: "Cache Miss",
    subtitle: "It remembers where you have been.",
    hint: "Trackers read your recent path. Doubling back is safer than running straight.",
    width: 21,
    height: 21,
    targetTime: 90,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o........H........o#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...S...............#",
      "#.########.##.#####.#",
      "#.########.##.#####.#",
      "#...................#",
      "#.##.##.#####.##.##.#",
      "#.##.##.#####.##.##.#",
      "#W........T.........#",
      "#.##.##.#####.##.##.#",
      "#.##.##.#####.##.##.#",
      "#...................#",
      "#.###~~.##.########.#",
      "#.#####.##.########.#",
      "#...............S...#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#o........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"rotate","cx":4,"cy":4,"size":5,"label":"Junction Beta"},
      {"type":"bridge","label":"Lower Span","cells":[[5,14],[6,14]]},
    ],
    secrets: [],
  },
  {
    id: "L09",
    number: 9,
    name: "Lockstep",
    subtitle: "Drop a wall. Buy a second.",
    hint: "Barrier terminals slam a bulkhead across a corridor. Use one to cut a pursuer off mid-chase.",
    width: 21,
    height: 21,
    targetTime: 92,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o........H........o#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#...................#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#-........S.........#",
      "#.#####.#####.#####.#",
      "#.#####.#####.#####.#",
      "#...I...........T...#",
      "#.#####.#####.#####.#",
      "#.#####.#####.#####.#",
      "#.........S.........#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...................#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#o........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"barrier","label":"Upper Bulkhead","cells":[[8,7],[9,7]]},
      {"type":"barrier","label":"Lower Bulkhead","cells":[[11,13],[12,13]]},
    ],
    secrets: [],
  },
  {
    id: "L10",
    number: 10,
    name: "Slipstream",
    subtitle: "Walls that move on your command.",
    hint: "Sliding walls shunt a whole segment aside — closing one corridor always opens another.",
    width: 21,
    height: 21,
    targetTime: 95,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o........H........o#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...I..S........N...#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...S...............#",
      "#%#####.##.##.#####.#",
      "#%#####.##.##.#####.#",
      "#****##...W......##.#",
      "#######.##.##.#####.#",
      "#######.##.##.#####.#",
      "#............S......#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...................#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#.........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"rotate","cx":7,"cy":7,"size":5,"label":"Junction Sigma"},
      {"type":"reveal","label":"Breach Seal","cells":[[1,9],[1,8]]},
      {"type":"slide","label":"Sector Slide","cells":[[8,15],[9,15]],"dx":0,"dy":1},
    ],
    secrets: [
      {"x":1,"y":10,"w":4,"h":1,"name":"Compartment A"},
    ],
  },
  {
    id: "L11",
    number: 11,
    name: "Ghost Sector",
    subtitle: "The map is lying to you.",
    hint: "Some terminals breach a sealed compartment. Bonus nodes are optional — the clock is not.",
    width: 21,
    height: 21,
    targetTime: 98,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o........H...##****#",
      "#.##.##.##.##.##%####",
      "#.##.##.##.##.##%####",
      "#...................#",
      "#.##.#####.########.#",
      "#.##.#####.########.#",
      "#...............S...#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#I......##N##......T#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...S........S......#",
      "#.#####.##.#####.##.#",
      "#.#####.##.#####.##.#",
      "#...................#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#o........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"reveal","label":"Breach Seal","cells":[[16,2],[16,3]]},
      {"type":"slide","label":"West Slide","cells":[[6,14],[6,15]],"dx":1,"dy":0},
      {"type":"rotate","cx":13,"cy":13,"size":5,"label":"Junction Kappa"},
    ],
    secrets: [
      {"x":16,"y":1,"w":4,"h":1,"name":"Compartment A"},
    ],
  },
  {
    id: "L12",
    number: 12,
    name: "Recursion",
    subtitle: "Every route you open closes another.",
    hint: "Three terminals, one cooldown. Decide what the maze should look like before you commit.",
    width: 21,
    height: 21,
    targetTime: 100,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#****##...H.........#",
      "#%#####.~~.##.##.##.#",
      "#%#####.##.##.~~.##.#",
      "#.........S.........#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#...S...........N...#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#o..I..S.....S.....o#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#.........T.........#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#.........o.........#",
      "#.##.##.##.##.#######",
      "#.##.##.##.##.#######",
      "#.........P.........#",
      "#####################",
    ],
    shifts: [
      {"type":"bridge","label":"Twin Spans","cells":[[8,2],[9,2],[14,3],[15,3]]},
      {"type":"reveal","label":"Breach Seal","cells":[[1,2],[1,3]]},
      {"type":"rotate","cx":7,"cy":10,"size":5,"label":"Junction West"},
      {"type":"rotate","cx":13,"cy":10,"size":5,"ccw":true,"label":"Junction East"},
    ],
    secrets: [
      {"x":1,"y":1,"w":4,"h":1,"name":"Compartment A"},
    ],
  },
  {
    id: "L13",
    number: 13,
    name: "Cascade",
    subtitle: "One command. Four walls.",
    hint: "Cascade terminals fire several reconfigurations at once. Read the whole board first.",
    width: 21,
    height: 21,
    targetTime: 105,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o......##****##...o#",
      "#.##.#####%#####.##.#",
      "#.##.#####%#####.##.#",
      "#...I.....S.....N...#",
      "#.#####.##.##.#####.#",
      "#.#####.##.##.#####.#",
      "#.........H.........#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#S......##.##......S#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#.........S.........#",
      "#.#####.##.##.#####.#",
      "#.#####.##.##.#####.#",
      "#...T...........W...#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#o........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"reveal","label":"Breach Seal","cells":[[10,2],[10,3]]},
      {"type":"rotate","cx":4,"cy":10,"size":5,"label":"Junction West"},
      {"type":"rotate","cx":16,"cy":10,"size":5,"ccw":true,"label":"Junction East"},
      {"type":"combo","label":"Cascade Core","parts":[{"type":"rotate","cx":7,"cy":13,"size":5},{"type":"rotate","cx":13,"cy":13,"size":5,"ccw":true}]},
    ],
    secrets: [
      {"x":10,"y":1,"w":4,"h":1,"name":"Compartment A"},
    ],
  },
  {
    id: "L14",
    number: 14,
    name: "Blackout",
    subtitle: "Five patrols and nowhere quiet.",
    hint: "Save a shift for the moment two drones converge. Rotating a junction can split them apart.",
    width: 21,
    height: 21,
    targetTime: 108,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#o........H........o#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#.........S.........#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#o..S...--..........#",
      "#######.##.##.##.##.#",
      "#######.##.##.##.##.#",
      "#****##I..S..N.....o#",
      "#%#####.##.##.##.##.#",
      "#%#####.##.##.##.##.#",
      "#..........--...S...#",
      "#.##.#####.#####%####",
      "#.##.#####.#####%####",
      "#...T........W##****#",
      "#.##.##.##.##.#######",
      "#.##.##.##.##.#######",
      "#.........P.........#",
      "#####################",
    ],
    shifts: [
      {"type":"combo","label":"Gate Cascade","parts":[{"type":"gate","cells":[[8,7],[9,7],[11,13],[12,13]]},{"type":"rotate","cx":4,"cy":10,"size":5}]},
      {"type":"reveal","label":"West Breach","cells":[[1,11],[1,12]]},
      {"type":"rotate","cx":10,"cy":10,"size":5,"label":"Junction Core"},
      {"type":"reveal","label":"East Breach","cells":[[16,15],[16,14]]},
    ],
    secrets: [
      {"x":1,"y":10,"w":4,"h":1,"name":"Compartment A"},
      {"x":16,"y":16,"w":4,"h":1,"name":"Compartment B"},
    ],
  },
  {
    id: "L15",
    number: 15,
    name: "Master Hack",
    subtitle: "Own the maze. Rewrite the pursuit.",
    hint: "Everything the grid has. Perfect Clear needs no deaths, every secret, and the target time.",
    width: 21,
    height: 21,
    targetTime: 115,
    rankThresholds: {"S+":1,"S":1.3,"A":1.7,"B":2.2},
    map: [
      "#####################",
      "#****##.......##****#",
      "#%########.#####%####",
      "#%########.#####%####",
      "#.........S.........#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...I.....H.....N...#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#o........S........o#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#...S..T.....W..S...#",
      "#.##.##.##.##.##.##.#",
      "#.##.##.##.##.##.##.#",
      "#...................#",
      "#.##.#####.#####.##.#",
      "#.##.#####.#####.##.#",
      "#o........P........o#",
      "#####################",
    ],
    shifts: [
      {"type":"combo","label":"Twin Breach","parts":[{"type":"reveal","cells":[[1,2],[1,3]]},{"type":"reveal","cells":[[16,2],[16,3]]}]},
      {"type":"combo","label":"Core Cascade","parts":[{"type":"rotate","cx":7,"cy":10,"size":5},{"type":"rotate","cx":13,"cy":10,"size":5,"ccw":true}]},
      {"type":"slide","label":"West Slide","cells":[[5,15],[6,15]],"dx":0,"dy":1},
      {"type":"rotate","cx":16,"cy":10,"size":5,"label":"East Junction"},
    ],
    secrets: [
      {"x":1,"y":1,"w":4,"h":1,"name":"Compartment A"},
      {"x":16,"y":1,"w":4,"h":1,"name":"Compartment B"},
    ],
  },
];

export const TOTAL_LEVELS = LEVELS.length;

/** @returns {object|undefined} */
export function getLevel(number) {
  return LEVELS[number - 1];
}
