const SEVERITY_LABEL = { fail: 'Critical Issues', warn: 'Warnings', info: 'Suggestions' };
const TOOL_URL = 'https://mattlivingston.com/tools/launch-doctor/';

export function buildReportData(vfs, ctx, issues, score) {
  return {
    productionUrl: ctx.productionUrl || null,
    timestamp: new Date().toISOString(),
    filesScanned: vfs.size,
    score: score.total,
    categories: score.categories,
    counts: score.counts,
    issues,
  };
}

export function toJson(reportData) {
  return JSON.stringify(reportData, null, 2);
}

function issueLine(issue) {
  const loc = issue.file ? `${issue.file}${issue.line ? `:${issue.line}` : ''}` : 'site-wide';
  return `- **[${issue.category}]** ${issue.title} _(${loc})_\n  ${issue.message}\n  Fix: ${issue.fix}`;
}

export function toMarkdown(reportData) {
  const { productionUrl, timestamp, filesScanned, score, categories, counts, issues } = reportData;
  const lines = [];
  lines.push('# Launch Doctor Report');
  lines.push('');
  lines.push(`**Score:** ${score}/100`);
  lines.push(`**Production URL:** ${productionUrl || '(not provided)'}`);
  lines.push(`**Files scanned:** ${filesScanned}`);
  lines.push(`**Generated:** ${timestamp}`);
  lines.push('');
  lines.push('## Category Breakdown');
  lines.push('');
  for (const [category, data] of Object.entries(categories)) {
    lines.push(`- **${category}:** ${data.score}/${data.weight} (${data.fail} fail, ${data.warn} warn, ${data.info} info)`);
  }
  lines.push('');
  lines.push(`## Critical Issues (${counts.fail || 0})`);
  lines.push('');
  const fails = issues.filter((i) => i.severity === 'fail');
  lines.push(fails.length ? fails.map(issueLine).join('\n') : '_None found._');
  lines.push('');
  lines.push(`## Warnings (${counts.warn || 0})`);
  lines.push('');
  const warns = issues.filter((i) => i.severity === 'warn');
  lines.push(warns.length ? warns.map(issueLine).join('\n') : '_None found._');
  lines.push('');
  lines.push(`## Suggestions (${counts.info || 0})`);
  lines.push('');
  const infos = issues.filter((i) => i.severity === 'info');
  lines.push(infos.length ? infos.map(issueLine).join('\n') : '_None found._');
  lines.push('');
  lines.push('## Generated Fix Files');
  lines.push('');
  lines.push('See the accompanying Fix Pack ZIP for suggested robots.txt, sitemap.xml, _headers, vercel.json, and 404.html files.');
  lines.push('');
  lines.push(`_Report generated by [Launch Doctor](${TOOL_URL}) on ${timestamp}._`);
  return lines.join('\n');
}
